# Copyright 2026 Binary Core LLC
# SPDX-License-Identifier: Apache-2.0

"""Variants: asset material, geometry, configuration and attribute variants; scene lighting
and model-selection variants; selecting, listing and removing them."""

from __future__ import annotations

from tests.golden.model import Scenario, Step, at


def _place(asset: str, name: str, group: str = "Props", x: float = 0.0,
           save: str | None = None) -> Step:
    return Step(
        "place_asset",
        {"asset_file_path": f"$lib/{asset}", "asset_name": name, "group": group, **at(x)},
        save=save, note=f"place {asset} as {name}",
    )


def _light(name: str, x: float, save: str) -> Step:
    return Step("create_light", {"light_type": "SphereLight", "light_name": name,
                                 **at(x, 3.0, 0.0)}, save=save, note=f"a light named {name}")


SCENARIOS = (
    Scenario(
        "variants/asset_material",
        "A material variant set on an asset: add, list, select per asset and per instance, remove.",
        (
            _place("lamp/lamp.usda", "Lamp", save="lamp"),
            _place("lamp/lamp.usda", "Lamp", x=2.0, save="lamp_2"),
            Step("create_material",
                 {"prim_path": "$lamp/asset/Base", "material_name": "red",
                  "base_color_r": 0.8, "base_color_g": 0.1, "base_color_b": 0.1,
                  "confirm_shared_modification": True},
                 note="a second material in the lamp, so there are two to choose from"),
            Step("add_asset_material_variant",
                 {"prim_path": "$lamp", "variant_set": "finish", "variant_name": "red",
                  "bindings": {"$lamp/asset/Shade": "$lamp/asset/mtl/red"}},
                 note="variant red: the Shade shows red"),
            Step("add_asset_material_variant",
                 {"prim_path": "$lamp", "variant_set": "finish", "variant_name": "brass",
                  "bindings": {"$lamp/asset/Shade": "$lamp/asset/mtl/brass"}},
                 note="variant brass: the Shade shows the shipped brass"),
            Step("list_variants", {"prim_path": "$lamp"}),
            Step("select_asset_variant",
                 {"prim_path": "$lamp", "variant_set": "finish", "variant_name": "red"},
                 note="every lamp shows red"),
            Step("select_asset_variant_for_instance",
                 {"prim_path": "$lamp_2", "variant_set": "finish", "variant_name": "brass"},
                 note="only the second lamp shows brass"),
            Step("remove_asset_variant",
                 {"prim_path": "$lamp", "variant_set": "finish", "variant_name": "red"},
                 note="remove the selected variant"),
            Step("list_variants", {"prim_path": "$lamp"}),
            Step("remove_asset_variant_set", {"prim_path": "$lamp", "variant_set": "finish"}),
            Step("list_variants", {"prim_path": "$lamp"}),
        ),
    ),
    Scenario(
        "variants/asset_geometry_lod",
        "A geometry (LOD) variant set built from the files in the asset folder.",
        (
            _place("lamp/lamp.usda", "Lamp", save="lamp"),
            Step("list_asset_geo_files", {"prim_path": "$lamp"}),
            Step("add_asset_geometry_variant",
                 {"prim_path": "$lamp", "variant_set": "lod", "variant_name": "low",
                  "payloads": {"/lamp": "./geo_low.usda"}},
                 note="extending a set that was never set up"),
            Step("setup_asset_geometry_variants",
                 {"prim_path": "$lamp", "variant_set": "lod",
                  "variants": {"high": "./geo.usda", "low": "./geo_low.usda"},
                  "default_variant": "high"},
                 note="set up high and low"),
            Step("select_asset_variant",
                 {"prim_path": "$lamp", "variant_set": "lod", "variant_name": "low"}),
            Step("add_asset_geometry_variant",
                 {"prim_path": "$lamp", "variant_set": "lod", "variant_name": "proxy",
                  "payloads": {"/lamp": "./geo_low.usda"}},
                 note="a third variant"),
            Step("setup_asset_geometry_variants",
                 {"prim_path": "$lamp", "variant_set": "lod2",
                  "variants": {"high": "./geo.usda", "missing": "./nope.usda"},
                  "default_variant": "high"},
                 note="a payload file that does not exist"),
            Step("list_variants", {"prim_path": "$lamp"}),
            Step("remove_asset_variant_set", {"prim_path": "$lamp", "variant_set": "lod"}),
        ),
    ),
    Scenario(
        "variants/asset_configuration",
        "A configuration variant set that turns parts on and off.",
        (
            _place("table.usda", "Table", "Furniture", save="table"),
            Step("add_asset_configuration_variant",
                 {"prim_path": "$table", "variant_set": "legs", "variant_name": "one_leg",
                  "activations": {"$table/asset/Leg_L": False}},
                 note="variant one_leg: Leg_L switched off"),
            Step("add_asset_configuration_variant",
                 {"prim_path": "$table", "variant_set": "legs", "variant_name": "all",
                  "activations": {"$table/asset/Leg_L": True}, "set_as_default": True},
                 note="variant all, made the default"),
            Step("select_asset_variant",
                 {"prim_path": "$table", "variant_set": "legs", "variant_name": "one_leg"}),
            Step("remove_asset_variant",
                 {"prim_path": "$table", "variant_set": "legs", "variant_name": "all"},
                 note="remove the default variant"),
            Step("remove_asset_variant",
                 {"prim_path": "$table", "variant_set": "legs", "variant_name": "one_leg"},
                 note="remove the last variant"),
            Step("list_variants", {"prim_path": "$table"}),
        ),
    ),
    Scenario(
        "variants/asset_attribute",
        "An attribute variant set that changes values on parts.",
        (
            _place("table.usda", "Table", "Furniture", save="table"),
            Step("add_asset_attribute_variant",
                 {"prim_path": "$table", "variant_set": "size", "variant_name": "big",
                  "overrides": {"$table/asset/Top": {"size": 1.5}}},
                 note="variant big: the Top's size 1.5"),
            Step("add_asset_attribute_variant",
                 {"prim_path": "$table", "variant_set": "size", "variant_name": "hidden_top",
                  "overrides": {"$table/asset/Top": {"visibility": "invisible"}}},
                 note="variant hidden_top"),
            Step("select_asset_variant",
                 {"prim_path": "$table", "variant_set": "size", "variant_name": "hidden_top"}),
            Step("set_prim_attribute",
                 {"prim_path": "$table/asset/Top", "attribute_name": "size", "value": 3.0},
                 note="a scene override on a value the variants set"),
            Step("add_asset_attribute_variant",
                 {"prim_path": "$table", "variant_set": "size", "variant_name": "small",
                  "overrides": {"$table/asset/Top": {"size": 0.5}}},
                 note="a new variant now masked by the scene override"),
            Step("add_asset_attribute_variant",
                 {"prim_path": "$table", "variant_set": "size", "variant_name": "small",
                  "overrides": {"$table/asset/Top": {"size": 0.5}},
                  "clear_masking_overrides": True},
                 note="clear the masking override first"),
            Step("list_variants", {"prim_path": "$table"}),
        ),
    ),
    Scenario(
        "variants/scene_lighting",
        "Scene lighting variants: attribute moods and a light selection.",
        (
            _light("Key", 0.0, "key"),
            _light("Fill", 2.0, "fill"),
            Step("add_scene_lighting_attribute_variant",
                 {"variant_set": "mood", "variant_name": "day",
                  "overrides": {"$key": {"inputs:intensity": 1000.0}}},
                 note="mood day"),
            Step("add_scene_lighting_attribute_variant",
                 {"variant_set": "mood", "variant_name": "night",
                  "overrides": {"$key": {"inputs:intensity": 50.0,
                                         "inputs:color": [0.4, 0.5, 1.0]}},
                  "set_as_default": True},
                 note="mood night, the default"),
            Step("add_scene_lighting_selection_variant",
                 {"variant_set": "rig", "variant_name": "key_only",
                  "activations": {"$key": True, "$fill": False}},
                 note="rig key_only: the fill is off"),
            Step("list_variants", {"prim_path": "/Scene/Lighting"}),
            Step("select_scene_variant",
                 {"prim_path": "/Scene/Lighting", "variant_set": "mood", "variant_name": "day"}),
            Step("remove_scene_variant",
                 {"prim_path": "/Scene/Lighting", "variant_set": "mood", "variant_name": "day"},
                 note="remove the selected mood"),
            Step("remove_scene_variant_set",
                 {"prim_path": "/Scene/Lighting", "variant_set": "rig"}),
            Step("list_variants", {"prim_path": "/Scene/Lighting"}),
        ),
    ),
    Scenario(
        "variants/model_selection",
        "A placement that can swap between models.",
        (
            _place("chair.usda", "Seat", "Furniture", save="seat"),
            Step("add_scene_model_selection_variant",
                 {"prim_path": "$seat", "variant_set": "model", "variant_name": "crate",
                  "asset_file_path": "$lib/crate.usda"},
                 note="the seat can also be a crate"),
            Step("add_scene_model_selection_variant",
                 {"prim_path": "$seat", "variant_set": "model", "variant_name": "chair_cm",
                  "asset_file_path": "$lib/chair_cm.usda"},
                 note="or the centimeter chair"),
            Step("list_variants", {"prim_path": "$seat"}),
            Step("select_scene_variant",
                 {"prim_path": "$seat", "variant_set": "model", "variant_name": "chair_cm"}),
            Step("remove_scene_variant",
                 {"prim_path": "$seat", "variant_set": "model", "variant_name": "crate"}),
            Step("remove_scene_variant_set", {"prim_path": "$seat", "variant_set": "model"},
                 note="remove the whole set: which model stays?"),
            Step("list_scene"),
        ),
    ),
    Scenario(
        "variants/refusals",
        "Variant calls that cannot work.",
        (
            _place("table.usda", "Table", "Furniture", save="table"),
            Step("add_asset_configuration_variant",
                 {"prim_path": "$table", "variant_set": "bad name", "variant_name": "x",
                  "activations": {"$table/asset/Leg_L": False}},
                 note="a set name with a space"),
            Step("add_asset_configuration_variant",
                 {"prim_path": "$table", "variant_set": "legs", "variant_name": "x",
                  "activations": {"$table/asset/Nope": False}},
                 note="a part that does not exist"),
            Step("add_asset_material_variant",
                 {"prim_path": "$table", "variant_set": "finish", "variant_name": "x",
                  "bindings": {"$table/asset/Top": "$table/asset/mtl/nope"}},
                 note="a material that does not exist"),
            Step("select_asset_variant",
                 {"prim_path": "$table", "variant_set": "nope", "variant_name": "x"},
                 note="a set that does not exist"),
            Step("remove_asset_variant",
                 {"prim_path": "$table", "variant_set": "nope", "variant_name": "x"}),
            Step("list_variants", {"prim_path": "/Scene/Nope"}),
            Step("add_asset_configuration_variant",
                 {"prim_path": "$table", "variant_set": "legs", "variant_name": "x",
                  "activations": {}},
                 note="no activations"),
        ),
    ),
    Scenario(
        "variants/geometry_lod_shipped",
        "LODs from an asset that ships both geometry files: listing, setup, extending, default.",
        (
            _place("lamp_lod/lamp_lod.usda", "LodLamp", save="lamp"),
            Step("list_variants", {"prim_path": "$lamp"}, note="the shipped LOD set"),
            Step("list_asset_geo_files", {"prim_path": "$lamp"}),
            Step("setup_asset_geometry_variants",
                 {"prim_path": "$lamp", "variant_set": "lod",
                  "variants": {"high": "./geo.usda", "low": "./geo_low.usda"},
                  "default_variant": "high"},
                 note="set up a BowerBot LOD set from the two files"),
            Step("add_asset_geometry_variant",
                 {"prim_path": "$lamp", "variant_set": "lod", "variant_name": "proxy",
                  "payloads": {"/lamp_lod": "./geo_low.usda"}, "set_as_default": True},
                 note="extend it with a proxy, made the default"),
            Step("select_asset_variant",
                 {"prim_path": "$lamp", "variant_set": "lod", "variant_name": "low"}),
            Step("list_variants", {"prim_path": "$lamp"}),
            Step("remove_asset_variant",
                 {"prim_path": "$lamp", "variant_set": "lod", "variant_name": "proxy"}),
            Step("list_asset_geo_files", {"prim_path": "/Scene/Nope"},
                 note="a placement that does not exist"),
        ),
    ),
    Scenario(
        "variants/asset_flags",
        "set_as_default, confirm_masked and clear_masking_overrides on every asset variant kind.",
        (
            _place("lamp/lamp.usda", "Lamp", save="lamp"),
            Step("create_material",
                 {"prim_path": "$lamp/asset/Base", "material_name": "red",
                  "base_color_r": 0.8, "base_color_g": 0.1, "base_color_b": 0.1},
                 note="a second material to switch to"),
            Step("add_asset_material_variant",
                 {"prim_path": "$lamp", "variant_set": "finish", "variant_name": "red",
                  "bindings": {"$lamp/asset/Shade": "$lamp/asset/mtl/red"},
                  "set_as_default": True, "confirm_masked": True},
                 note="a material variant made the default, masking confirmed"),
            Step("add_asset_material_variant",
                 {"prim_path": "$lamp", "variant_set": "finish", "variant_name": "brass",
                  "bindings": {"$lamp/asset/Shade": "$lamp/asset/mtl/brass"},
                  "clear_masking_overrides": True},
                 note="another, clearing masking overrides first"),
            Step("add_asset_configuration_variant",
                 {"prim_path": "$lamp", "variant_set": "parts", "variant_name": "no_shade",
                  "activations": {"$lamp/asset/Shade": False}, "set_as_default": True,
                  "clear_masking_overrides": True},
                 note="a configuration variant made the default"),
            Step("add_asset_configuration_variant",
                 {"prim_path": "$lamp", "variant_set": "parts", "variant_name": "all",
                  "activations": {"$lamp/asset/Shade": True}, "confirm_masked": True}),
            Step("add_asset_attribute_variant",
                 {"prim_path": "$lamp", "variant_set": "tint", "variant_name": "hidden_base",
                  "overrides": {"$lamp/asset/Base": {"visibility": "invisible"}},
                  "set_as_default": True, "confirm_masked": True},
                 note="an attribute variant made the default"),
            Step("list_variants", {"prim_path": "$lamp"}),
            Step("add_asset_material_variant",
                 {"prim_path": "$lamp", "variant_set": "finish!", "variant_name": "x",
                  "bindings": {"$lamp/asset/Shade": "$lamp/asset/mtl/red"}},
                 note="an invalid set name"),
            Step("remove_asset_variant",
                 {"prim_path": "/Scene/Nope", "variant_set": "finish", "variant_name": "red"},
                 note="a placement that does not exist"),
            Step("remove_asset_variant_set", {"prim_path": "/Scene/Nope", "variant_set": "finish"}),
            Step("select_asset_variant",
                 {"prim_path": "/Scene/Nope", "variant_set": "finish", "variant_name": "red"}),
            Step("select_asset_variant_for_instance",
                 {"prim_path": "/Scene/Nope", "variant_set": "finish", "variant_name": "red"}),
            Step("remove_asset_variant_set", {"prim_path": "$lamp", "variant_set": "tint"}),
        ),
    ),
    Scenario(
        "variants/scene_flags",
        "Scene lighting and model-selection variants: flags, defaults, repairs and refusals.",
        (
            _light("Key", 0.0, "key"),
            _light("Fill", 2.0, "fill"),
            _place("chair.usda", "Seat", "Furniture", 4.0, save="seat"),
            Step("set_prim_attribute",
                 {"prim_path": "$key", "attribute_name": "inputs:intensity", "value": 700.0},
                 note="a scene value on the key light"),
            Step("add_scene_lighting_attribute_variant",
                 {"variant_set": "mood", "variant_name": "dim",
                  "overrides": {"$key": {"inputs:intensity": 10.0}}},
                 note="masked by the value just set"),
            Step("add_scene_lighting_attribute_variant",
                 {"variant_set": "mood", "variant_name": "dim",
                  "overrides": {"$key": {"inputs:intensity": 10.0}}, "confirm_masked": True},
                 note="author it anyway"),
            Step("add_scene_lighting_attribute_variant",
                 {"variant_set": "mood", "variant_name": "bright",
                  "overrides": {"$key": {"inputs:intensity": 2000.0}},
                  "clear_masking_overrides": True},
                 note="clear the masking value first"),
            Step("add_scene_lighting_selection_variant",
                 {"variant_set": "rig", "variant_name": "fill_only",
                  "activations": {"$key": False, "$fill": True}, "set_as_default": True,
                  "clear_masking_overrides": True},
                 note="a light selection made the default"),
            Step("add_scene_lighting_selection_variant",
                 {"variant_set": "rig", "variant_name": "both",
                  "activations": {"$key": True, "$fill": True}, "confirm_masked": True}),
            Step("add_scene_lighting_selection_variant",
                 {"variant_set": "rig", "variant_name": "chair",
                  "activations": {"$seat": False}},
                 note="a target outside /Scene/Lighting"),
            Step("add_scene_model_selection_variant",
                 {"prim_path": "$seat", "variant_set": "model", "variant_name": "unfrozen",
                  "asset_file_path": "$lib/unfrozen.usda"},
                 note="an alternative whose root is not frozen"),
            Step("add_scene_model_selection_variant",
                 {"prim_path": "$seat", "variant_set": "model", "variant_name": "unfrozen",
                  "asset_file_path": "$lib/unfrozen.usda", "fix_root_transforms": True,
                  "set_as_default": True},
                 note="retry with the repair, made the default"),
            Step("add_scene_model_selection_variant",
                 {"prim_path": "$seat", "variant_set": "model", "variant_name": "cube",
                  "asset_file_path": "$lib/rooted_mesh.usda", "fix_root_prim": True},
                 note="an alternative with a geometry root, wrapped"),
            Step("add_scene_model_selection_variant",
                 {"prim_path": "$seat", "variant_set": "model", "variant_name": "nope",
                  "asset_file_path": "$lib/nope.usda"},
                 note="an alternative that does not exist"),
            Step("list_variants", {"prim_path": "$seat"}),
            Step("select_scene_variant",
                 {"prim_path": "/Scene/Nope", "variant_set": "model", "variant_name": "cube"}),
            Step("remove_scene_variant",
                 {"prim_path": "/Scene/Nope", "variant_set": "model", "variant_name": "cube"}),
            Step("remove_scene_variant_set", {"prim_path": "/Scene/Nope", "variant_set": "model"}),
        ),
    ),
)
